# Generated by Django 3.1.4 on 2020-12-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('iin', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=150, null=True)),
                ('black_book', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Credit',
                'verbose_name_plural': 'Credits',
            },
        ),
    ]
