# Generated by Django 3.1.4 on 2020-12-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_auto_20201215_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='age',
        ),
        migrations.RemoveField(
            model_name='program',
            name='validation_credits',
        ),
        migrations.AddField(
            model_name='program',
            name='age_max',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='age_min',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='max_credits_sum',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='min_credits_sum',
            field=models.IntegerField(null=True),
        ),
    ]
