# Generated by Django 3.1.4 on 2020-12-17 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0005_auto_20201217_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='iin',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1000000)]),
            preserve_default=False,
        ),
    ]
