# Generated by Django 3.1.4 on 2020-12-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0007_auto_20201217_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='iin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='iin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='program',
            name='age_max',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='age_min',
            field=models.IntegerField(null=True),
        ),
    ]
