# Generated by Django 3.1.4 on 2020-12-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0008_auto_20201217_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
