# Generated by Django 3.1.4 on 2020-12-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0009_auto_20201217_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
