# Generated by Django 3.1.4 on 2020-12-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0011_auto_20201221_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='iin',
            field=models.CharField(max_length=12),
        ),
    ]
