# Generated by Django 3.1.4 on 2020-12-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0013_auto_20201221_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='iin',
            field=models.CharField(max_length=13),
        ),
    ]
