# Generated by Django 3.1.4 on 2020-12-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0014_auto_20201221_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='iin',
            field=models.CharField(db_index=True, max_length=13),
        ),
    ]
